name: KingdomUHC
version: '${project.version}'
main: fr.juststop.dev.kingdomuhc.KingdomUHC
api-version: 1.8.8
load: STARTUP
commands:
  kingdom:
    description: The main command of the plugin.
    aliases:
      - ki
      - kd
      - king
  world:
    description: Allow the manipulation of the game world.
    aliases:
      - w
  language:
    description: Edits the in-game messages.
    aliases:
      - lang